services:
    protonmail-bridge:
        volumes:
            - bridge_data:/data/bridge
            - security_data:/data/security
        ports:
            - 1025:8025/tcp
            - 1143:8143/tcp
        restart: unless-stopped
        image: ghcr.io/eltariel/proton-bridge-container:latest
volumes:
    bridge_data:
    security_data:
